
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "08db480f9387aab3c93c4f256b7c4c726a7314fb",
 "version": "2022.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
