from ..hydrologicproc import addprocess
#This method loads a GR4J template into the GUI
def loadCanshield(self):
    try:
        table = self.dlg.table_hydroprocess #Get the hydrological processes table

        #Sets the model parameters 
        self.dlg.combo_method.setCurrentText("ORDERED_SERIES")
        self.dlg.combo_interpo.setCurrentText("INTERP_NEAREST_NEIGHBOR")
        self.dlg.combo_routing.setCurrentText("ROUTE_DIFFUSIVE_WAVE")
        self.dlg.combo_catchment.setCurrentText("ROUTE_TRI_CONVOLUTION")

        self.dlg.combo_evapo.setCurrentText("PET_HARGREAVES_1985")
        self.dlg.combo_owevapo.setCurrentText("PET_HARGREAVES_1985")
        self.dlg.combo_swcanopy.setCurrentText("SW_CANOPY_CORR_STATIC")
        self.dlg.combo_rainsnowfrac.setCurrentText("RAINSNOW_DINGMAN")
        self.dlg.combo_potentialmelt.setCurrentText("POTMELT_DEGREE_DAY") 
        self.dlg.combo_precipicept.setCurrentText("PRECIP_ICEPT_LAI")
        self.dlg.combo_monthlyinterpo.setCurrentText("MONTHINT_LINEAR_MID")
        self.dlg.combo_lakestorage.setCurrentText("LAKE_STORAGE")
        self.dlg.combo_soilmod.setCurrentText("SOIL_MULTILAYER")
        self.dlg.spin_soilmod.setValue(3)

        #Sets the hydrological processes
        for i in range(15):
            addprocess(self)

        combo_proc = table.cellWidget(0,0)
        combo_proc.setCurrentText("SnowRefreeze")
        combo_alg = table.cellWidget(0,1)
        combo_alg.setCurrentText("FREEZE_DEGREE_DAY")
        combo_from = table.cellWidget(0,2)
        combo_from.setCurrentText("SNOW_LIQ")
        combo_to = table.cellWidget(0,3)
        combo_to.setCurrentText("SNOW")

        combo_proc = table.cellWidget(1,0)
        combo_proc.setCurrentText("Precipitation")
        combo_alg = table.cellWidget(1,1)
        combo_alg.setCurrentText("PRECIP_RAVEN")
        combo_from = table.cellWidget(1,2)
        combo_from.setCurrentText("ATMOS_PRECIP")
        combo_to = table.cellWidget(1,3)
        combo_to.setCurrentText("MULTIPLE")

        combo_proc = table.cellWidget(2,0)
        combo_proc.setCurrentText("CanopyEvaporation")
        combo_alg = table.cellWidget(2,1)
        combo_alg.setCurrentText("CANEVP_MAXIMUM")
        combo_from = table.cellWidget(2,2)
        combo_from.setCurrentText("CANOPY")
        combo_to = table.cellWidget(2,3)
        combo_to.setCurrentText("ATMOSPHERE")
        
        combo_proc = table.cellWidget(3,0)
        combo_proc.setCurrentText("CanopySublimation")
        combo_alg = table.cellWidget(3,1)
        combo_alg.setCurrentText("SUBLIM_MAXIMUM")
        combo_from = table.cellWidget(3,2)
        combo_from.setCurrentText("CANOPY_SNOW")
        combo_to = table.cellWidget(3,3)
        combo_to.setCurrentText("ATMOSPHERE")

        combo_proc = table.cellWidget(4,0)
        combo_proc.setCurrentText("SnowBalance")
        combo_alg = table.cellWidget(4,1)
        combo_alg.setCurrentText("SNOBAL_TWO_LAYER")
        combo_from = table.cellWidget(4,2)
        combo_from.setCurrentText("MULTIPLE")
        combo_to = table.cellWidget(4,3)
        combo_to.setCurrentText("MULTIPLE")

        combo_proc = table.cellWidget(5,0)
        combo_proc.setCurrentText("Abstraction")
        combo_alg = table.cellWidget(5,1)
        combo_alg.setCurrentText("ABST_FILL")
        combo_from = table.cellWidget(5,2)
        combo_from.setCurrentText("PONDED_WATER")
        combo_to = table.cellWidget(5,3)
        combo_to.setCurrentText("DEPRESSION")

        combo_proc = table.cellWidget(6,0)
        combo_proc.setCurrentText("OpenWaterEvaporation")
        combo_alg = table.cellWidget(6,1)
        combo_alg.setCurrentText("OPEN_WATER_EVAP")
        combo_from = table.cellWidget(6,2)
        combo_from.setCurrentText("DEPRESSION")
        combo_to = table.cellWidget(6,3)
        combo_to.setCurrentText("ATMOSPHERE")

        combo_proc = table.cellWidget(7,0)
        combo_proc.setCurrentText("Infiltration")
        combo_alg = table.cellWidget(7,1)
        combo_alg.setCurrentText("INF_HBV")
        combo_from = table.cellWidget(7,2)
        combo_from.setCurrentText("PONDED_WATER")
        combo_to = table.cellWidget(7,3)
        combo_to.setCurrentText("MULTIPLE")
        
        combo_proc = table.cellWidget(8,0)
        combo_proc.setCurrentText("LakeRelease")
        combo_alg = table.cellWidget(8,1)
        combo_alg.setCurrentText("LAKEREL_LINEAR")
        combo_from = table.cellWidget(8,2)
        combo_from.setCurrentText("LAKE_STORAGE")
        combo_to = table.cellWidget(8,3)
        combo_to.setCurrentText("SURFACE_WATER")

        combo_proc = table.cellWidget(9,0)
        combo_proc.setCurrentText("SoilEvaporation")
        combo_alg = table.cellWidget(9,1)
        combo_alg.setCurrentText("SOILEVAP_ROOT")
        combo_from = table.cellWidget(9,2)
        combo_from.setCurrentText("SOIL[0]")
        combo_to = table.cellWidget(9,3)
        combo_to.setCurrentText("ATMOSPHERE")

        combo_proc = table.cellWidget(10,0)
        combo_proc.setCurrentText("Percolation")
        combo_alg = table.cellWidget(10,1)
        combo_alg.setCurrentText("PERC_GAWSER_CONSTRAIN")
        combo_from = table.cellWidget(10,2)
        combo_from.setCurrentText("SOIL[0]")
        combo_to = table.cellWidget(10,3)
        combo_to.setCurrentText("SOIL[1]")

        combo_proc = table.cellWidget(11,0)
        combo_proc.setCurrentText("Percolation")
        combo_alg = table.cellWidget(11,1)
        combo_alg.setCurrentText("PERC_GAWSER_CONSTRAIN")
        combo_from = table.cellWidget(11,2)
        combo_from.setCurrentText("SOIL[1]")
        combo_to = table.cellWidget(11,3)
        combo_to.setCurrentText("SOIL[2]")

        combo_proc = table.cellWidget(12,0)
        combo_proc.setCurrentText("Baseflow")
        combo_alg = table.cellWidget(12,1)
        combo_alg.setCurrentText("BASE_THRESH_POWER")
        combo_from = table.cellWidget(12,2)
        combo_from.setCurrentText("SOIL[0]")
        combo_to = table.cellWidget(12,3)
        combo_to.setCurrentText("SURFACE_WATER")

        combo_proc = table.cellWidget(13,0)
        combo_proc.setCurrentText("Baseflow")
        combo_alg = table.cellWidget(13,1)
        combo_alg.setCurrentText("BASE_THRESH_POWER")
        combo_from = table.cellWidget(13,2)
        combo_from.setCurrentText("SOIL[1]")
        combo_to = table.cellWidget(13,3)
        combo_to.setCurrentText("SURFACE_WATER")

        combo_proc = table.cellWidget(14,0)
        combo_proc.setCurrentText("Baseflow")
        combo_alg = table.cellWidget(14,1)
        combo_alg.setCurrentText("BASE_THRESH_POWER")
        combo_from = table.cellWidget(14,2)
        combo_from.setCurrentText("SOIL[2]")
        combo_to = table.cellWidget(14,3)
        combo_to.setCurrentText("SURFACE_WATER")

        table.resizeColumnsToContents() #Resizes the width of the column automatically
        
        print("Canadian Shield template loaded.")
        self.iface.messageBar().pushSuccess("Success", "Loaded Canadian Shield template successfully")
    except Exception as e:
        print('An error occured while loading Canadian Shield template.')
        print(e)  