from ..hydrologicproc import addprocess

#This method loads a GR4J template into the GUI
def loadGr4j(self):
    try:
        table = self.dlg.table_hydroprocess #Get the hydrological processes table

        #Sets the model parameters 
        self.dlg.combo_method.setCurrentText("ORDERED_SERIES")
        self.dlg.combo_interpo.setCurrentText("INTERP_NEAREST_NEIGHBOR")
        self.dlg.combo_routing.setCurrentText("ROUTE_NONE")
        self.dlg.combo_catchment.setCurrentText("ROUTE_DUMP")

        self.dlg.combo_evapo.setCurrentText("PET_DATA")
        self.dlg.combo_rainsnowfrac.setCurrentText("RAINSNOW_DINGMAN")
        self.dlg.combo_potentialmelt.setCurrentText("POTMELT_DEGREE_DAY")  
        self.dlg.combo_orotemp.setCurrentText("OROCORR_SIMPLELAPSE")
        self.dlg.combo_oroprecip.setCurrentText("OROCORR_SIMPLELAPSE")
        self.dlg.combo_soilmod.setCurrentText("SOIL_MULTILAYER")
        self.dlg.spin_soilmod.setValue(4)
        self.dlg.chk_snaphydro.setChecked(True)

        #Sets the hydrological processes
        for i in range(15):
            addprocess(self)

        combo_proc = table.cellWidget(0,0)
        combo_proc.setCurrentText("Precipitation")
        combo_alg = table.cellWidget(0,1)
        combo_alg.setCurrentText("PRECIP_RAVEN")
        combo_from = table.cellWidget(0,2)
        combo_from.setCurrentText("ATMOS_PRECIP")
        combo_to = table.cellWidget(0,3)
        combo_to.setCurrentText("MULTIPLE")

        combo_proc = table.cellWidget(1,0)
        combo_proc.setCurrentText("SnowTempEvolve")
        combo_alg = table.cellWidget(1,1)
        combo_alg.setCurrentText("SNOTEMP_NEWTONS")
        combo_from = table.cellWidget(1,2)
        combo_from.setCurrentText("SNOW_TEMP")
    
        combo_proc = table.cellWidget(2,0)
        combo_proc.setCurrentText("SnowBalance")
        combo_alg = table.cellWidget(2,1)
        combo_alg.setCurrentText("SNOBAL_CEMA_NEIGE")
        combo_from = table.cellWidget(2,2)
        combo_from.setCurrentText("SNOW")
        combo_to = table.cellWidget(2,3)
        combo_to.setCurrentText("PONDED_WATER")
        
        combo_proc = table.cellWidget(3,0)
        combo_proc.setCurrentText("OpenWaterEvaporation")
        combo_alg = table.cellWidget(3,1)
        combo_alg.setCurrentText("OPEN_WATER_EVAP")
        combo_from = table.cellWidget(3,2)
        combo_from.setCurrentText("PONDED_WATER")
        combo_to = table.cellWidget(3,3)
        combo_to.setCurrentText("ATMOSPHERE")

        combo_proc = table.cellWidget(4,0)
        combo_proc.setCurrentText("Infiltration")
        combo_alg = table.cellWidget(4,1)
        combo_alg.setCurrentText("INF_GR4J")
        combo_from = table.cellWidget(4,2)
        combo_from.setCurrentText("PONDED_WATER")
        combo_to = table.cellWidget(4,3)
        combo_to.setCurrentText("MULTIPLE")

        combo_proc = table.cellWidget(5,0)
        combo_proc.setCurrentText("SoilEvaporation")
        combo_alg = table.cellWidget(5,1)
        combo_alg.setCurrentText("SOILEVAP_GR4J")
        combo_from = table.cellWidget(5,2)
        combo_from.setCurrentText("SOIL[0]")
        combo_to = table.cellWidget(5,3)
        combo_to.setCurrentText("ATMOSPHERE")

        combo_proc = table.cellWidget(6,0)
        combo_proc.setCurrentText("Percolation")
        combo_alg = table.cellWidget(6,1)
        combo_alg.setCurrentText("PERC_GR4J")
        combo_from = table.cellWidget(6,2)
        combo_from.setCurrentText("SOIL[0]")
        combo_to = table.cellWidget(6,3)
        combo_to.setCurrentText("SOIL[2]")

        combo_proc = table.cellWidget(7,0)
        combo_proc.setCurrentText("Flush")
        combo_alg = table.cellWidget(7,1)
        combo_alg.setCurrentText("RAVEN_DEFAULT")
        combo_from = table.cellWidget(7,2)
        combo_from.setCurrentText("SURFACE_WATER")
        combo_to = table.cellWidget(7,3)
        combo_to.setCurrentText("SOIL[2]")
        
        #NEED MODIFICATION IN GUI TO SUPPORT SPLIT COMMAND
        combo_proc = table.cellWidget(8,0)
        combo_proc.setCurrentText("Split")
        combo_alg = table.cellWidget(8,1)
        combo_alg.setCurrentText("RAVEN_DEFAULT")
        # combo_from = table.cellWidget(8,2)
        # combo_from.setCurrentText("PONDED_WATER")
        # combo_to = table.cellWidget(8,3)
        # combo_to.setCurrentText("MULTIPLE")

        combo_proc = table.cellWidget(9,0)
        combo_proc.setCurrentText("Convolve")
        combo_alg = table.cellWidget(9,1)
        combo_alg.setCurrentText("CONVOL_GR4J_1")
        combo_from = table.cellWidget(9,2)
        combo_from.setCurrentText("CONVOLUTION[0]")
        combo_to = table.cellWidget(9,3)
        combo_to.setCurrentText("SOIL[1]")

        combo_proc = table.cellWidget(10,0)
        combo_proc.setCurrentText("Convolve")
        combo_alg = table.cellWidget(10,1)
        combo_alg.setCurrentText("CONVOL_GR4J_2")
        combo_from = table.cellWidget(10,2)
        combo_from.setCurrentText("CONVOLUTION[1]")
        combo_to = table.cellWidget(10,3)
        combo_to.setCurrentText("SOIL[2]")

        combo_proc = table.cellWidget(11,0)
        combo_proc.setCurrentText("Percolation")
        combo_alg = table.cellWidget(11,1)
        combo_alg.setCurrentText("PERC_GR4JEXCH")
        combo_from = table.cellWidget(11,2)
        combo_from.setCurrentText("SOIL[1]")
        combo_to = table.cellWidget(11,3)
        combo_to.setCurrentText("SOIL[3]")

        combo_proc = table.cellWidget(12,0)
        combo_proc.setCurrentText("Percolation")
        combo_alg = table.cellWidget(12,1)
        combo_alg.setCurrentText("PERC_GR4JEXCH2")
        combo_from = table.cellWidget(12,2)
        combo_from.setCurrentText("SOIL[2]")
        combo_to = table.cellWidget(12,3)
        combo_to.setCurrentText("SOIL[3]")

        combo_proc = table.cellWidget(13,0)
        combo_proc.setCurrentText("Flush")
        combo_alg = table.cellWidget(13,1)
        combo_alg.setCurrentText("RAVEN_DEFAULT")
        combo_from = table.cellWidget(13,2)
        combo_from.setCurrentText("SOIL[2]")
        combo_to = table.cellWidget(13,3)
        combo_to.setCurrentText("SURFACE_WATER")

        combo_proc = table.cellWidget(14,0)
        combo_proc.setCurrentText("Baseflow")
        combo_alg = table.cellWidget(14,1)
        combo_alg.setCurrentText("BASE_GR4J")
        combo_from = table.cellWidget(14,2)
        combo_from.setCurrentText("SOIL[1]")
        combo_to = table.cellWidget(14,3)
        combo_to.setCurrentText("SURFACE_WATER")

        table.resizeColumnsToContents() #Resizes the width of the column automatically
        
        print("GR4J template loaded.")
        self.iface.messageBar().pushSuccess("Success", "Loaded GR4J template successfully")
    except Exception as e:
        print('An error occured while loading GR4J template.')
        print(e)  