#This method loads a UBCWM template into the GUI
def loadUbcwm(self):
    try:
        table = self.dlg.table_hydroprocess #Get the hydrological processes table

        #Sets the model parameters 
        self.dlg.combo_method.setCurrentText("ORDERED_SERIES")
        self.dlg.combo_interpo.setCurrentText("INTERP_NEAREST_NEIGHBOR")
        self.dlg.combo_routing.setCurrentText("ROUTE_NONE")
        self.dlg.combo_catchment.setCurrentText("ROUTE_DUMP")
        self.dlg.combo_evapo.setCurrentText("PET_MONTHLY_FACTOR")
        self.dlg.combo_owevapo.setCurrentText("PET_MONTHLY_FACTOR")
        self.dlg.combo_swradation.setCurrentText("SW_RAD_UBCWM")
        self.dlg.combo_swcloud.setCurrentText("SW_CLOUD_CORR_UBCWM")
        self.dlg.combo_swcanopy.setCurrentText("SW_CANOPY_CORR_UBCWM")
        self.dlg.combo_lwradation.setCurrentText("LW_RAD_UBCWM")
        self.dlg.combo_windspeed.setCurrentText("WINDVEL_UBCWM")
        self.dlg.combo_rainsnowfrac.setCurrentText("RAINSNOW_UBCWM")
        self.dlg.combo_potentialmelt.setCurrentText("POTMELT_UBCWM")    
        self.dlg.combo_orotemp.setCurrentText("OROCORR_UBCWM")
        self.dlg.combo_oroprecip.setCurrentText("OROCORR_UBCWM2")
        self.dlg.combo_oropet.setCurrentText("OROCORR_UBCWM")
        self.dlg.combo_cloudcover.setCurrentText("CLOUDCOV_UBCWM")
        self.dlg.combo_precipicept.setCurrentText("PRECIP_ICEPT_USER")
        self.dlg.combo_monthlyinterpo.setCurrentText("MONTHINT_LINEAR_21")
        self.dlg.combo_soilmod.setCurrentText("SOIL_MULTILAYER")
        self.dlg.spin_soilmod.setValue(6)
        self.dlg.chk_snaphydro.setChecked(True)

        #Sets the hydrological processes
        for i in range(15):
            self.addTableRow()

        combo_proc = table.cellWidget(0,0)
        combo_proc.setCurrentText("SnowAlbedoEvolve")
        combo_alg = table.cellWidget(0,1)
        combo_alg.setCurrentText("SNOALB_UBCWM")

        combo_proc = table.cellWidget(1,0)
        combo_proc.setCurrentText("SnowBalance")
        combo_alg = table.cellWidget(1,1)
        combo_alg.setCurrentText("SNOBAL_UBCWM")
        combo_from = table.cellWidget(1,2)
        combo_from.setCurrentText("MULTIPLE")
        combo_to = table.cellWidget(1,3)
        combo_to.setCurrentText("MULTIPLE")

        combo_proc = table.cellWidget(2,0)
        combo_proc.setCurrentText("Flush")
        combo_alg = table.cellWidget(2,1)
        combo_alg.setCurrentText("RAVEN_DEFAULT")
        combo_from = table.cellWidget(2,2)
        combo_from.setCurrentText("PONDED_WATER")
        combo_to = table.cellWidget(2,3)
        combo_to.setCurrentText("SOIL[4]")
        checkconditional = table.cellWidget(2,4)
        checkconditional.setChecked(True)
        combo_basedtype = table.cellWidget(2,5)
        combo_basedtype.setCurrentText("HRU_TYPE")
        combo_comparison = table.cellWidget(2,6)
        combo_comparison.setCurrentText("IS")
        txt_hrutype = table.cellWidget(2,7)
        txt_hrutype.setText("GLACIER")

        combo_proc = table.cellWidget(3,0)
        combo_proc.setCurrentText("GlacierMelt")
        combo_alg = table.cellWidget(3,1)
        combo_alg.setCurrentText("GMELT_UBC")
        combo_from = table.cellWidget(3,2)
        combo_from.setCurrentText("GLACIER_ICE")
        combo_to = table.cellWidget(3,3)
        combo_to.setCurrentText("PONDED_WATER")

        combo_proc = table.cellWidget(4,0)
        combo_proc.setCurrentText("Precipitation")
        combo_alg = table.cellWidget(4,1)
        combo_alg.setCurrentText("PRECIP_RAVEN")
        combo_from = table.cellWidget(4,2)
        combo_from.setCurrentText("ATMOS_PRECIP")
        combo_to = table.cellWidget(4,3)
        combo_to.setCurrentText("MULTIPLE")

        combo_proc = table.cellWidget(5,0)
        combo_proc.setCurrentText("SoilEvaporation")
        combo_alg = table.cellWidget(5,1)
        combo_alg.setCurrentText("SOILEVAP_UBC")
        combo_from = table.cellWidget(5,2)
        combo_from.setCurrentText("MULTIPLE")
        combo_to = table.cellWidget(5,3)
        combo_to.setCurrentText("ATMOSPHERE")

        combo_proc = table.cellWidget(6,0)
        combo_proc.setCurrentText("Infiltration")
        combo_alg = table.cellWidget(6,1)
        combo_alg.setCurrentText("INF_UBC")
        combo_from = table.cellWidget(6,2)
        combo_from.setCurrentText("PONDED_WATER")
        combo_to = table.cellWidget(6,3)
        combo_to.setCurrentText("MULTIPLE")

        combo_proc = table.cellWidget(7,0)
        combo_proc.setCurrentText("Flush")
        combo_alg = table.cellWidget(7,1)
        combo_alg.setCurrentText("RAVEN_DEFAULT")
        combo_from = table.cellWidget(7,2)
        combo_from.setCurrentText("SURFACE_WATER")
        combo_to = table.cellWidget(7,3)
        combo_to.setCurrentText("SOIL[4]")
        checkconditional = table.cellWidget(7,4)
        checkconditional.setChecked(True)
        combo_basedtype = table.cellWidget(7,5)
        combo_basedtype.setCurrentText("HRU_TYPE")
        combo_comparison = table.cellWidget(7,6)
        combo_comparison.setCurrentText("IS_NOT")
        txt_hrutype = table.cellWidget(7,7)
        txt_hrutype.setText("LAKE")

        combo_proc = table.cellWidget(8,0)
        combo_proc.setCurrentText("GlacierInfiltration")
        combo_alg = table.cellWidget(8,1)
        combo_alg.setCurrentText("GINFIL_UBCWM")
        combo_from = table.cellWidget(8,2)
        combo_from.setCurrentText("PONDED_WATER")
        combo_to = table.cellWidget(8,3)
        combo_to.setCurrentText("MULTIPLE")

        combo_proc = table.cellWidget(9,0)
        combo_proc.setCurrentText("Percolation")
        combo_alg = table.cellWidget(9,1)
        combo_alg.setCurrentText("PERC_LINEAR_ANALYTIC")
        combo_from = table.cellWidget(9,2)
        combo_from.setCurrentText("SOIL[1]")
        combo_to = table.cellWidget(9,3)
        combo_to.setCurrentText("SOIL[4]")

        combo_proc = table.cellWidget(10,0)
        combo_proc.setCurrentText("Percolation")
        combo_alg = table.cellWidget(10,1)
        combo_alg.setCurrentText("PERC_LINEAR_ANALYTIC")
        combo_from = table.cellWidget(10,2)
        combo_from.setCurrentText("SOIL[4]")
        combo_to = table.cellWidget(10,3)
        combo_to.setCurrentText("SOIL[5]")

        combo_proc = table.cellWidget(11,0)
        combo_proc.setCurrentText("Baseflow")
        combo_alg = table.cellWidget(11,1)
        combo_alg.setCurrentText("BASE_LINEAR")
        combo_from = table.cellWidget(11,2)
        combo_from.setCurrentText("SOIL[5]")
        combo_to = table.cellWidget(11,3)
        combo_to.setCurrentText("SURFACE_WATER")

        combo_proc = table.cellWidget(12,0)
        combo_proc.setCurrentText("Baseflow")
        combo_alg = table.cellWidget(12,1)
        combo_alg.setCurrentText("BASE_LINEAR")
        combo_from = table.cellWidget(12,2)
        combo_from.setCurrentText("SOIL[2]")
        combo_to = table.cellWidget(12,3)
        combo_to.setCurrentText("SURFACE_WATER")

        combo_proc = table.cellWidget(13,0)
        combo_proc.setCurrentText("Baseflow")
        combo_alg = table.cellWidget(13,1)
        combo_alg.setCurrentText("BASE_LINEAR")
        combo_from = table.cellWidget(13,2)
        combo_from.setCurrentText("SOIL[3]")
        combo_to = table.cellWidget(13,3)
        combo_to.setCurrentText("SURFACE_WATER")

        combo_proc = table.cellWidget(14,0)
        combo_proc.setCurrentText("GlacierRelease")
        combo_alg = table.cellWidget(14,1)
        combo_alg.setCurrentText("GRELEASE_LINEAR")
        combo_from = table.cellWidget(14,2)
        combo_from.setCurrentText("GLACIER")
        combo_to = table.cellWidget(14,3)
        combo_to.setCurrentText("SURFACE_WATER")

        table.resizeColumnsToContents() #Resizes the width of the column automatically
        
        print("UBCWM template loaded.")
        self.iface.messageBar().pushSuccess("Success", "Loaded UBCWM template successfully")
    except Exception as e:
        print('An error occured while loading UBCWM template.')
        print(e)  